# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.23.0"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/souvap-workflow.yaml"
      - "defaults/stages.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"
      - "jobs/semantic-release-env.yaml"
  - project: 'univention/dist/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'

renovate:
  stage: "package"
  variables:
    LOG_LEVEL: debug
    RENOVATE_CONFIG_FILE: renovate.yaml
  before_script:
    - curl -o /tmp/helm.tar.gz https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
    - tar -zxvf /tmp/helm.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

lint-pre-commit:
  before_script:
    - helm repo add bitnami "https://charts.bitnami.com/bitnami"
