# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.36.2"
    file:
      - "defaults/nubus-workflow.yaml"
      - "defaults/stages.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/harbor-malware-scan.yaml"
  - project: 'univention/infrastructure/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'

variables:
  SKIP_UPDATE_HELM_VALUES: "1"
  AUTO_TRIGGER_TESTS:
    description: |
      Deployment and e2e test run will be triggered automatically if this is set
      to "yes".
    value: "no"
    options:
      - "yes"
      - "no"
  DEPLOY_NAMESPACE:
    description: "The namespace to deploy into."
    value: "ci-${CI_COMMIT_REF_SLUG}"
  DEPLOY_SUBDOMAIN:
    description: "The subdomain to prepend during the deployment."
    value: "${CI_COMMIT_REF_SLUG}"
  TESTRUNNER_VERSION:
    description: |
      Allows to specify a custom tag to use for the e2e-tests testrunner image.
      Intended to help with testing a branch of the e2e-tests repository.
    value: "latest"

renovate:
  stage: "package"
  variables:
    LOG_LEVEL: debug
    RENOVATE_CONFIG_FILE: renovate.yaml
  before_script:
    - curl -O https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
    - sha256sum -c $HELM_SHA256_SUM
    - tar -zxvf helm-v3.14.3-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_TASK == "renovate"'
      when: always
    - when: never

lint-pre-commit:
  before_script:
    - helm repo add bitnami "https://charts.bitnami.com/bitnami"


deploy-and-test:
  stage: deploy
  allow_failure: true
  needs:
    - job: publish-chart-external
      artifacts: false
    - job: pre-semantic-release
      artifacts: true
  trigger:
    include:
      - local: .gitlab-ci/deploy-and-test.yaml
    forward:
      pipeline_variables: true
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$AUTO_TRIGGER_TESTS == "yes"'
      when: on_success
    - when: manual
