# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.31.0"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/nubus-workflow.yaml"
      - "defaults/stages.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "jobs/semantic-release-env.yaml"
  - project: 'univention/dist/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'

variables:
  SKIP_UPDATE_HELM_VALUES: "1"
  DEPLOY_NAMESPACE:
    description: "The namespace to deploy into."
    value: "ci-${CI_COMMIT_REF_SLUG}"
  DEPLOY_SUBDOMAIN:
    description: "The subdomain to prepend during the deployment."
    value: "${CI_COMMIT_REF_SLUG}"

renovate:
  stage: "package"
  variables:
    LOG_LEVEL: debug
    RENOVATE_CONFIG_FILE: renovate.yaml
  before_script:
    - curl -O https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
    - sha256sum -c $HELM_SHA256_SUM
    - tar -zxvf helm-v3.14.3-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

lint-pre-commit:
  before_script:
    - helm repo add bitnami "https://charts.bitnami.com/bitnami"

deploy-gaia:
  stage: "deploy"
  image: "registry.opencode.de/bmi/opendesk/components/platform-development/images/helm:1.0.1\
          @sha256:d38f41b88374e055332860018f2936db8807b763caf6089735db0484cbb2842a"
  # TODO: Make the job required once we did gain enough confidence
  allow_failure: true
  script:
    - cd ci
    - export CHART_VERSION=${RELEASE_VERSION}
    - export REVIEW_PREFIX=${DEPLOY_SUBDOMAIN}
    - helmfile -n "${DEPLOY_NAMESPACE}" apply --skip-diff-on-install
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://${DEPLOY_SUBDOMAIN}.portal.review.gaia.open-desk.cloud
    on_stop: stop-deployment
    auto_stop_in: 1 day
    deployment_tier: development
  resource_group: review-${CI_COMMIT_REF_SLUG}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stop-deployment:
  stage: "deploy"
  when: manual
  image: "registry.opencode.de/bmi/opendesk/components/platform-development/images/helm:1.0.1\
          @sha256:d38f41b88374e055332860018f2936db8807b763caf6089735db0484cbb2842a"
  script:
    - kubectl delete namespace "ci-${CI_COMMIT_REF_SLUG}" --wait
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
