---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: '^.*\.patch'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args:
          # Allow custom tags like Gitlab's "!reference" tag.
          - --unsafe
        exclude: ^helm/.+/templates/
      - id: trailing-whitespace
      - id: "end-of-file-fixer"
        exclude: "^helm/.+/README.md$"

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://gitlab.com/univention/pre-commit-hooks/docker-compose-check
    rev: 7702a8801a158b8595569dd29e2dd655d8a08310
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.20
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=helm
          - --template-files=README.md.gotmpl
