# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
include:
  - local: .gitlab-ci/deploy-and-test.yaml

deploy-gaia:
  environment:
    name: ${CI_COMMIT_REF_SLUG}/nubus-plain
    url: https://plain-${DEPLOY_SUBDOMAIN}.portal.review.gaia.open-desk.cloud
    on_stop: stop-deployment
    auto_stop_in: 3 hours
    deployment_tier: development
  resource_group: gaia-ci-plain-${CI_COMMIT_REF_SLUG}
  variables:
    HELMFILE_ENVIRONMENT: plain
  before_script:
    - export DEPLOY_NAMESPACE="ci-plain-${CI_COMMIT_REF_SLUG}"
    - export DEPLOY_SUBDOMAIN="plain-${DEPLOY_SUBDOMAIN}"

wait-for-bootstrap:
  before_script:
    - export DEPLOY_NAMESPACE="ci-plain-${CI_COMMIT_REF_SLUG}"
    - export DEPLOY_SUBDOMAIN="plain-${DEPLOY_SUBDOMAIN}"

stop-deployment:
  environment:
    name: ${CI_COMMIT_REF_SLUG}/nubus-plain
    action: stop
  before_script:
    - export DEPLOY_NAMESPACE="ci-plain-${CI_COMMIT_REF_SLUG}"

configure-tests:
  before_script:
    - export DEPLOY_NAMESPACE="ci-plain-${CI_COMMIT_REF_SLUG}"
    - export DEPLOY_SUBDOMAIN="plain-${DEPLOY_SUBDOMAIN}"
