# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

kind: Secret
apiVersion: v1
metadata:
  name: certificates-ci-tls
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.certificate | quote }}
  tls.key: {{ .Values.key | quote }}

---
kind: Secret
apiVersion: v1
metadata:
  name: nubus-keycloak-extensions-proxy-tls
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.certificate | quote }}
  tls.key: {{ .Values.key | quote }}

---
kind: Secret
apiVersion: v1
metadata:
  name: nubus-portal-tls
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.certificate | quote }}
  tls.key: {{ .Values.key | quote }}
