# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-external-secret
type: Opaque
stringData:
  adminPassword: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "adminPassword" | sha1sum | quote }}
  userPassword: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "userPassword" | sha1sum | quote }}
  replicationPasswordKey: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "replicationPasswordKey" | sha1sum | quote }}
  guardian: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "guardian" | sha1sum | quote }}
  keycloak: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "keycloak" | sha1sum | quote }}
  keycloak-extensions: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "keycloak-extensions" | sha1sum | quote }}
  notifications: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "notifications" | sha1sum | quote }}
  umc: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "umc" | sha1sum | quote }}
  umcsession: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "umcsession" | sha1sum | quote }}
---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio-external-secret
type: Opaque
stringData:
  portal-consumer-access-key: "portal-consumer"
  portal-consumer-secret-key:  {{ derivePassword 1 "long" .Values.masterPassword "nubus" "ext-minio-portal-consumer" | sha1sum | quote }}
  portal-server-access-key: "portal-server"
  portal-server-secret-key: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "ext-minio-portal-server" | sha1sum | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-external-user-provisioning
type: Opaque
stringData:
  portal-consumer: {{ printf "username=portal-consumer\npassword=%s\ndisabled=false\npolicies=nubus-readwrite\nsetPolicies=false" (derivePassword 1 "long" .Values.masterPassword "nubus" "ext-minio-portal-consumer" | sha1sum) | quote }}
  portal-server: {{ printf "username=portal-server\npassword=%s\ndisabled=false\npolicies=nubus-read\nsetPolicies=false" (derivePassword 1 "long" .Values.masterPassword "nubus" "ext-minio-portal-server" | sha1sum) | quote }}
---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: nats-external-secret
type: Opaque
stringData:
  nats-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-password" | sha1sum) | quote }}
  nats-provisioning-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-provisioning-password" | sha1sum) | quote }}
  nats-dispatcher-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-dispatcher-password" | sha1sum) | quote }}
  nats-udm-transformer-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-udm-transformer-password" | sha1sum) | quote }}
  nats-prefill-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-prefill-password" | sha1sum) | quote }}
  nats-udm-listener-password: {{ printf "nats_%s" (derivePassword 1 "long" .Values.masterPassword "nubus" "nats-udm-listener-password" | sha1sum) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-external-admin-credentials
type: Opaque
stringData:
  root-user: "admin"
  root-password: {{ derivePassword 1 "long" .Values.masterPassword "nubus" "minio-external-root-password" | sha1sum | quote }}
