# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
apiVersion: "v2"
name: "ums"
description: "The Univention Management Stack"
type: "application"
version: "0.0.1"

dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"

  # guardian related chart(s)
  - name: "guardian-authorization-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-authorization-api.enabled"
    tags:
      - pre-release

  - name: "guardian-management-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-management-api.enabled"
    tags:
      - pre-release

  - name: "guardian-management-ui"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-management-ui.enabled"
    tags:
      - pre-release

  - name: "open-policy-agent"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "open-policy-agent.enabled"
    tags:
      - pre-release

  # ldap-server related chart(s)
  - name: "ldap-notifier"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    version: "0.*"
    condition: "ldap-notifier.enabled"

  - name: "ldap-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    #version: "0.*"
    version: "0.10.0-pre-feat-bsi-compliance"
    condition: "ldap-server.enabled"

  # portal related chart(s)
  - name: "minio"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "^13.x.x"
    condition: "minio.enabled"

  - name: "notifications-api"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: notifications-api.enabled
    tags:
      - pre-release

  - name: "portal-frontend"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-frontend.enabled"

  - name: "portal-listener"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-listener.enabled"

  - name: "portal-server"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-server.enabled"

  - name: "selfservice-listener"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/selfservice-listener/helm"
    condition: "selfservice-listener.enabled"

  # provisioning related chart(s)
  - name: "provisioning"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/helm"
    version: "0.*"
    condition: "provisioning.enabled"
    tags:
      - pre-release

  - name: "udm-listener"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/helm"
    version: "0.*"
    condition: "provisioning.enabled"
    tags:
      - pre-release

  # keycloak related chart(s)
  - name: "ums-keycloak"
    alias: "keycloak"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/univention-keycloak"
    version: "1.*"
    condition: "keycloak.enabled"

  - name: "keycloak-extensions"
    repository: "oci://gitregistry.knut.univention.de/univention/components/keycloak-extensions/helm"
    version: "0.*"
    condition: "keycloak-extensions.enabled"

  - name: "ums-keycloak-bootstrap"
    alias: "keycloak-bootstrap"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/univention-keycloak-bootstrap"
    version: "1.*"
    condition: "keycloak-bootstrap.enabled"

  - name: "postgresql"
    alias: "keycloak-postgresql"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "^12.x.x"
    condition: "keycloak-postgresql.enabled"

  # stack-data related chart(s)
  - name: "stack-data-swp"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "0.*"
    condition: "stack-data-swp.enabled"

  - name: "stack-data-ums"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "0.*"
    condition: "stack-data-ums.enabled"

  # stack-gateway related chart(s)
  - name: "nginx"
    alias: "stack-gateway"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "^15.x.x"
    condition: "stack-gateway.enabled"

  # udm-rest-api related chart(s)
  - name: "udm-rest-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/helm"
    version: "0.*"
    condition: "udm-rest-api.enabled"

  # umc related chart(s)
  - name: "umc-gateway"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "0.*"
    condition: "umc-gateway.enabled"

  - name: "umc-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "0.*"
    condition: "umc-server.enabled"
