# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

apiVersion: "v2"
name: "ums"
description: "The Univention Management Stack"
type: "application"
version: "0.0.1"

dependencies:
  - name: "portal-frontend"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-frontend.enabled"
  - name: "portal-listener"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-frontend.enabled"
  - name: "portal-server"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-server.enabled"
  - name: "selfservice-listener"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/selfservice-listener/helm"
    condition: "selfservice-listener.enabled"
  - name: "store-dav"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-store-dav/helm"
    version: "0.*"
    condition: "store-dav.enabled"

  - name: "notifications-api"
    version: "0.*"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "notifications-api.enabled"
    tags:
      - pre-release

  - name: "ldap-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    version: "0.*"
    condition: "ldap-server.enabled"
  - name: "ldap-notifier"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    version: "0.*"
    condition: "ldap-notifier.enabled"
  - name: "udm-rest-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/helm"
    version: "0.*"
    condition: "udm-rest-api.enabled"

  - name: "umc-gateway"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "0.*"
    condition: "umc-gateway.enabled"
  - name: "umc-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "0.*"
    condition: "umc-server.enabled"

  - name: "ums-keycloak"
    alias: "keycloak"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/univention-keycloak"
    version: "1.*"
    condition: "keycloak.enabled"
  - name: "keycloak-extensions"
    repository: "oci://gitregistry.knut.univention.de/univention/components/keycloak-extensions/helm"
    version: "0.*"
    condition: "keycloak-extensions.enabled"
  - name: "ums-keycloak-bootstrap"
    alias: "keycloak-bootstrap"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/univention-keycloak-bootstrap"
    version: "1.*"
    condition: "keycloak-bootstrap.enabled"
  - name: "postgresql"
    alias: "keycloak-postgresql"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "~12.7.1"
    condition: "keycloak-postgresql.enabled"

  - name: "provisioning"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/helm"
    version: "0.*"
    condition: "provisioning.enabled"
    tags:
      - pre-release

  - name: "guardian-authorization-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-authorization-api.enabled"
    tags:
      - pre-release
  - name: "guardian-management-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-management-api.enabled"
    tags:
      - pre-release
  - name: "guardian-management-ui"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "guardian-management-ui.enabled"
    tags:
      - pre-release
  - name: "open-policy-agent"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/guardian-helm/helm"
    version: "0.*"
    condition: "open-policy-agent.enabled"
    tags:
      - pre-release

  - name: "stack-data-ums"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "0.*"
    condition: "stack-data-ums.enabled"
  - name: "stack-data-swp"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "0.*"
    condition: "stack-data-swp.enabled"

  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "0.*"
