# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

apiVersion: v2
name: ums
description: The Univention Management Stack
type: application
version: 0.0.1

dependencies:
  - name: "portal-frontend"
    version: "^0.9.2"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-frontend.enabled"
  - name: "portal-listener"
    version: "^0.9.2"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-frontend.enabled"
  - name: "portal-server"
    version: "^0.9.2"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "portal-server.enabled"
  - name: "store-dav"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-store-dav/helm"
    version: "^0.2.0"
    condition: "store-dav.enabled"

  - name: "notifications-api"
    version: "^0.9.2"
    repository: "oci://gitregistry.knut.univention.de/univention/components/univention-portal/helm"
    condition: "notifications-api.enabled"
    tags:
      - pre-release

  - name: "ldap-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    version: "^0.8.2"
    condition: "ldap-server.enabled"
  - name: "ldap-notifier"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/helm"
    version: "^0.8.2"
    condition: "ldap-notifier.enabled"
  - name: "udm-rest-api"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/helm"
    version: "^0.5.2"
    condition: "udm-rest-api.enabled"

  - name: "umc-gateway"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "^0.6.4"
    condition: "umc-gateway.enabled"
  - name: "umc-server"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-umc/helm"
    version: "^0.6.4"
    condition: "umc-server.enabled"

  - name: "stack-data-ums"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "^0.41.8"
    condition: "stack-data-ums.enabled"
  - name: "stack-data-swp"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/stack-data/helm"
    version: "^0.41.8"
    condition: "stack-data-swp.enabled"

  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.6.0"
