# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

# This file contains settings which are useful for development deployments.
# The intention is to make it easy to apply these settings by including this
# file with the "--values" flag to the helm command.

global:
  configMapUcrForced: "ums-ucr-overrides"

ums:
  # TODO: Decide about the right home for this. We have a duplication in our
  # development environment. We should most likely have a utility chart or
  # extension to an existing one to make it easy to provide UCR values which
  # override the defaults.
  ucrForcedValues: |-
    directory/manager/rest/ldap-connection/user-read/start-tls: 0
    directory/manager/rest/show-tracebacks: true
    portal/auth-mode: ucs
    umc/http/show_tracebacks: true
    password/quality/length/min: 8
    password/quality/required/chars:
    password/quality/forbidden/chars:
    password/quality/credit/digits: 0
    password/quality/credit/upper: 0
    password/quality/credit/other: 0
    password/quality/credit/lower: 0
    password/quality/mspolicy: false

stack-data-swp:
  stackDataSwp:
    extraDataFiles:
      99-dev-env-overrides.yaml: |
        {{ with .Values.stackDataContext }}
        ---
        action: "modify"
        module: "portals/entry"
        position: "cn=login-ucs,cn=entry,cn=portals,cn=univention,{{ .ldapBase }}"
        properties:
          activated: true
        {{ end }}
