# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

stack-data-swp:
  stackDataSwp:
    extraDataFiles:
      99-dev-env-overrides.yaml: |
        {{ with .Values.stackDataContext }}
        ---
        action: "modify"
        module: "portals/entry"
        position: "cn=login-ucs,cn=entry,cn=portals,cn=univention,{{ .ldapBase }}"
        properties:
          activated: true
        {{ end }}
