# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

notifications-api:
  ingress:
    host: localhost

portal-frontend:
  ingress:
    host: localhost

portal-listener:
  portalListener:
    adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
    umcGetUrl: "http://umc-server/get"
    umcSessionUrl: "http://umc-server/get/session-info"
    ldapSecret: "password"
    machineSecret: "password"
  store-dav:
    bundled: false

portal-server:
  portalServer:
    adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
    ucsInternalUrl: "http://portal-server:password@store-dav/portal-data"
    umcGetUrl: "http://umc-server/get"
    umcSessionUrl: "http://umc-server/get/session-info"
  ingress:
    host: localhost

tags:
  pre-release: true
