# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

# This file currently contains the set of required values to make a local
# deployment into an evaluation cluster possible. It assumes that the ingress
# controller "ingress-nginx" is in use.
#
# Long term this file shall be reduced again to the minimal set of required
# values so that "helm lint" can be successfully executed.

global:
  configMapUcrDefaults: "ums-stack-data-ums-ucr"
  configMapUcr: "ums-stack-data-swp-ucr"
  configMapUcrForced: null

ldap-notifier:
  volumes:
    claims:
      shared-data: "shared-data-ums-ldap-server-0"
      shared-run: "shared-run-ums-ldap-server-0"

ldap-server:
  ldapServer:
    ldapSecret: "password"
    ldapBaseDn: "dc=univention-organization,dc=intranet"

  extraVolumes:
    - name: "opendesk-schemas"
      configMap:
        name: "ums-stack-data-swp-schemas"

  extraVolumeMounts:
    - name: "opendesk-schemas"
      mountPath: "/var/lib/univention-ldap-local/local-schema/opendeskFileshare.schema"
      subPath: "opendeskFileshare.schema"
    - name: "opendesk-schemas"
      mountPath: "/var/lib/univention-ldap-local/local-schema/opendeskKnowledgemanagement.schema"
      subPath: "opendeskKnowledgemanagement.schema"
    - name: "opendesk-schemas"
      mountPath: "/var/lib/univention-ldap-local/local-schema/opendeskLearnmanagement.schema"
      subPath: "opendeskLearnmanagement.schema"
    - name: "opendesk-schemas"
      mountPath: "/var/lib/univention-ldap-local/local-schema/opendeskLivecollaboration.schema"
      subPath: "opendeskLivecollaboration.schema"
    - name: "opendesk-schemas"
      mountPath: "/var/lib/univention-ldap-local/local-schema/opendeskProjectmanagement.schema"
      subPath: "opendeskProjectmanagement.schema"

notifications-api:
  ingress:
    host: localhost
    tls:
      enabled: false

portal-frontend:
  ingress:
    host: localhost
    tls:
      enabled: false

portal-listener:
  portalListener:
    assetsRoot: "http://portal-listener:password@ums-store-dav/portal-assets/"
    adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
    ucsInternalUrl: "http://portal-server:password@ums-store-dav/portal-data"
    udmApiUrl: "http://ums-udm-rest-api/udm/"
    udmApiUsername: "cn=admin"
    umcGetUrl: "http://ums-umc-server/get"
    umcSessionUrl: "http://ums-umc-server/get/session-info"
    ldapHost: "ums-ldap-server"
    notifierServer: "ums-ldap-notifier"
    ldapBaseDn: "dc=univention-organization,dc=intranet"
    portalDefaultDn: "cn=domain,cn=portal,cn=portals,cn=univention,dc=univention-organization,dc=intranet"
    ldapHostDn: "cn=admin,dc=univention-organization,dc=intranet"
    ldapSecret: "password"
    machineSecret: "password"
    tlsMode: "off"

  store-dav:
    bundled: false

portal-server:
  portalServer:
    adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
    ucsInternalUrl: "http://portal-server:password@ums-store-dav/portal-data"
    umcGetUrl: "http://ums-umc-server/get"
    umcSessionUrl: "http://ums-umc-server/get/session-info"
  ingress:
    host: localhost
    tls:
      enabled: false

stack-data-ums:
  stackDataUms:
    udmApiPassword: "password"
    udmApiUrl: "http://ums-udm-rest-api/udm/"
    loadDevData: true
  stackDataContext:
    initialPasswordAdministrator: "password"
    ldapHost: "ums-ldap-server"

stack-data-swp:
  stackDataSwp:
    udmApiPassword: "password"
    udmApiUrl: "http://ums-udm-rest-api/udm/"
    loadDevData: true
  stackDataContext:
    userPassword: "univention"
    adminPassword: "univention"

store-dav:
  storeDav:
    auth:
      basicAuth:
        portal-server: "password"
        portal-listener: "password"
  ingress:
    host: localhost
    tls:
      enabled: false

udm-rest-api:
  udmRestApi:
    ldapSecret: "password"
    machineSecret: "password"
  ingress:
    host: localhost
    tls:
      enabled: false

tags:
  pre-release: true
