# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
tags:
  # -- Components which are not yet fully integrated or not yet feature complete
  # are flagged with this tag. The intention is to make it easy to follow the
  # development progress for evaluation purposes.
  pre-release: false

<<<<<<< HEAD
=======
provisioning:
  resources:
    dispatcher:
      limits:
        memory: "1Gi"
      requests:
        cpu: "10m"
        memory: "32Mi"
    prefill:
      limits:
        memory: "1Gi"
      requests:
        cpu: "10m"
        memory: "32Mi"
    api:
      limits:
        memory: "1Gi"
      requests:
        cpu: "10m"
        memory: "32Mi"
  nats:
    resources:
      limits:
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "64Mi"
    reloader:
      resources:
        limits:
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
    natsBox:
      resources:
        limits:
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"

ldap-server:
  limits:
  memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

udm-rest-api:
  limits:
  memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

>>>>>>> 15175d5 (feat: use BSI compliant charts)
minio:
  persistence:
    enabled: true
    storageClass: ""
    mountPath: /bitnami/minio/data
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  networkPolicy:
    enabled: false

  defaultBuckets: "ums"

  provisioning:
    enabled: true
    cleanupAfterFinished:
      enabled: true
    extraCommands:
      - "mc anonymous set download provisioning/ums/portal-assets"
    buckets:
      - name: "ums"
        versioning: false
        withLock: false
    policies:
      - name: "ums-bucket-policy"
        statements:
          - resources:
              - "arn:aws:s3:::ums"
            effect: "Allow"
            actions:
              - "s3:*"
          - resources:
              - "arn:aws:s3:::ums/*"
            effect: "Allow"
            actions:
              - "s3:*"
