# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
nubusStackDataUms:
  templateContext:
    loadDevData: true
    initialPasswordDefaultUser: '{{ include "nubusTemplates.credentials.ldap.users.idp.password" . }}'
    initialPasswordDefaultAdmin: '{{ include "nubusTemplates.credentials.ldap.users.admin.password" . }}'

  stackDataUms:
    extraDataFiles:
      # TODO: These workarounds should be removed over time.

      # TODO: The "{{` `}}" avoids the templating via Helm. We need a
      # "extraDataFiles" which does not run the content through "tpl" anymore.

      99-plain-nubus-workarounds.yaml: |
        {{`
        ---
        action: "modify"
        module: "portals/entry"
        position: "cn=login-saml,cn=entry,cn=portals,cn=univention,{{ ldapBaseDn }}"
        properties:
          activated: true
        `}}

      99-dev-users.yaml: |
        {{`
        {% if loadDevData %}
        ---
        action: "create"
        module: "users/user"
        position: 'cn=users,{{ ldapBaseDn }}'
        properties:
          username: "default.user"
          firstname: "Default"
          lastname: "User"
          password: "{{ initialPasswordDefaultUser }}"
          mailPrimaryAddress: "default.user@{{ externalMailDomain }}"
          overridePWHistory: true
          overridePWLength: true
        ---
        action: "create"
        module: "users/user"
        position: 'cn=users,{{ ldapBaseDn }}'
        properties:
          username: "default.admin"
          firstname: "Default"
          lastname: "Admin"
          primaryGroup: 'cn=Domain Admins,cn=groups,{{ ldapBaseDn }}'
          password: "{{ initialPasswordDefaultAdmin }}"
          guardianRoles:
            - "guardian:builtin:super-admin"
          mailPrimaryAddress: "default.admin@{{ externalMailDomain }}"
          overridePWHistory: true
          overridePWLength: true
        {% endif %}
        `}}
