# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
environments:
  default:
    values:
      - gaia-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - local-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
helmDefaults:
  # Do not set 'wait=true' or 'waitForJobs=true'. It lets the keycloak-bootstrap job vanish.

  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 1200

repositories:
  - name: nubus-dev
    url: artifacts.software-univention.de/nubus-dev/charts
    oci: true
  - name: maildev
    url: https://christianhuth.github.io/helm-charts

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificate: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.crt" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}
        key: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.key" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}

  - name: nubus
    chart: {{ if .Values.dev.useLocalChart }}../helm/nubus{{ else }}nubus-dev/nubus{{ end }}
    version: {{ env "CHART_VERSION" | default "*" | quote }}
    values:
      - ./ci-values.yaml.gotmpl
      - ./dev-values.yaml

  - name: maildev
    chart: maildev/maildev
    version: 1.2.2
    values:
      - ./maildev-values.yaml.gotmpl
