# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
environments:
  default:
    values:
      - gaia-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - local-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
repositories:
  - name: univention
    url: registry.souvap-univention.de/souvap/tooling/charts/univention
    oci: true

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificate: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.crt" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}
        key: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.key" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}

  - name: ums
    chart: {{ if .Values.dev.useLocalChart }}../helm/ums{{ else }}univention/ums{{ end }}
    version: {{ env "CHART_VERSION" | default "*" | quote }}
    values:
      # TODO: Pending cleanup once the value refactoring has been merged.
      # See: https://git.knut.univention.de/univention/customers/dataport/upx/ums-stack/-/merge_requests/23
      - ../helm/ums/linter_values.yaml
      - ./public-images-values.yaml
      - ../helm/ums/dev_values.yaml
      - ./stage1-values.yaml
      - ./domain-values.yaml.gotmpl
      - ./secret-values.yaml.gotmpl
