# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
environments:
  default:
    values:
      - gaia-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - local-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
repositories:
  - name: univention
    url: registry.souvap-univention.de/souvap/tooling/charts/univention
    oci: true

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificate: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.crt" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}
        key: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.key" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}

  - name: ums
    chart: univention/ums
    version: {{ env "CHART_VERSION" | default "0.14.0" }}
    values:
      - ../helm/ums/linter_values.yaml
      - ../helm/ums/public_images_values.yaml
      - ../helm/ums/dev_values.yaml
      - ../helm/ums/stage1_values.yaml
      - ./domain-values.yaml.gotmpl
