# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
environments:

  # The default configuration is a bare Nubus deployment without openDesk extensions
  # but with a few adjustments for the Gaia cluster.
  default:
    values:
      - default-state-values.yaml.gotmpl
      - gaia-state-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

  # Configuration for a local or custom deployment.
  #
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - default-state-values.yaml.gotmpl
      - local-state-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
helmDefaults:
  # Do not set 'wait=true' or 'waitForJobs=true'. It lets the keycloak-bootstrap job vanish.

  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 1200

repositories:
  - name: nubus-dev
    url: artifacts.software-univention.de/nubus-dev/charts
    oci: true
  - name: maildev
    url: https://christianhuth.github.io/helm-charts

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificates-values.yaml.gotmpl

  - name: nubus
    chart: {{ if .Values.dev.useLocalChart }}../helm/nubus{{ else }}nubus-dev/nubus{{ end }}
    version: {{ env "CHART_VERSION" | default "*" | quote }}
    values:
      - ./ci-values.yaml.gotmpl
      - ./dev-values.yaml.gotmpl
      {{- if .Values.toggles.nextcloudExtension }}
      - ./nextcloud-extension-values.yaml.gotmpl
      {{- end }}
      {{- if .Values.toggles.loadTest }}
      - ./load-test-values.yaml.gotmpl
      {{- end }}

  - name: maildev
    chart: maildev/maildev
    version: 1.2.2
    values:
      - ./maildev-values.yaml.gotmpl
