# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
environments:
  default:
    values:
      - gaia-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - local-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
repositories:
  - name: nubus-dev
    url: artifacts.software-univention.de/nubus-dev/charts
    oci: true

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificate: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.crt" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}
        key: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.key" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}

  - name: nubus
    chart: {{ if .Values.dev.useLocalChart }}../helm/nubus{{ else }}nubus-dev/nubus{{ end }}
    version: {{ env "CHART_VERSION" | default "*" | quote }}
    values:
      - ./ci-values.yaml.gotmpl
      # - ./dev-values.yaml
      # TODO: Pending cleanup once the value refactoring has been merged.
      # See: https://git.knut.univention.de/univention/customers/dataport/upx/ums-stack/-/merge_requests/23
      # - ../helm/nubus/linter_values.yaml
      # - ./public-images-values.yaml
      # - ../helm/ums/dev_values.yaml
      # - ./stage1-values.yaml
      # - ./domain-values.yaml.gotmpl
      # - ./secret-values.yaml.gotmpl
