# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
environments:

  # The default configuration is a bare Nubus deployment without openDesk extensions
  # but with a few adjustments for the Gaia cluster.
  default:
    values:
      - gaia-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

  # Extension of the default values, adding the nextcloud Nubus integration package.
  # More information can be found in the integration repository:
  # https://git.knut.univention.de/univention/components/packaged-integrations/nextcloud
  nextcloud:
    values:
      - gaia-values.yaml.gotmpl
      - nextcloud-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

  # Extension of the default values, customized for large load testing scenarios
  loadtest:
    values:
      - gaia-values.yaml.gotmpl
      - loadtest-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

  # Configuration for a local or custom deployment.
  #
  # Copy "gaia-values.yaml" to "local-values.yaml" and run helmfile with "-e
  # local" for local experimentation e.g. with other clusters.
  local:
    values:
      - local-values.yaml.gotmpl
      - reviewPrefix: {{ env "REVIEW_PREFIX" | default .Namespace }}

---
helmDefaults:
  # Do not set 'wait=true' or 'waitForJobs=true'. It lets the keycloak-bootstrap job vanish.

  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 1200

repositories:
  - name: nubus-dev
    url: artifacts.software-univention.de/nubus-dev/charts
    oci: true
  - name: maildev
    url: https://christianhuth.github.io/helm-charts

releases:
  - name: certificate
    chart: ./certificate
    values:
      - certificate: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.crt" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}
        key: {{ printf "ref+k8s://v1/Secret/%s/certificates-ci-tls/tls.key" .Values.cluster.namespaces.ci | fetchSecretValue | quote }}

  - name: nubus
    chart: {{ if .Values.dev.useLocalChart }}../helm/nubus{{ else }}nubus-dev/nubus{{ end }}
    version: {{ env "CHART_VERSION" | default "*" | quote }}
    values:
      - ./ci-values.yaml.gotmpl
      - ./dev-values.yaml.gotmpl
      {{- if hasKey .Values "releaseValues" }}
      - {{ .Values.releaseValues.nubus | toYaml | nindent 8 }}
      {{- end }}

  - name: maildev
    chart: maildev/maildev
    version: 1.2.2
    values:
      - ./maildev-values.yaml.gotmpl
