# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
apiVersion: "v2"
name: "nubus"
description: "Univention Nubus"
type: "application"
version: "1.0.0"

dependencies:
  - name: "nubus-common"
    version: "^0.8.x"
    repository: "oci://artifacts.software-univention.de/nubus/charts"

  - name: "postgresql"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "^12.x.x"
    condition: "postgresql.enabled"

  - name: "minio"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "14.7.0"
    condition: "minio.enabled"

  - name: "guardian"
    alias: "nubusGuardian"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.18.0"
    condition: "nubusGuardian.enabled"

  - name: "license-import"
    alias: "nubusLicenseImport"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.1.0"
    condition: "nubusLicenseImport.enabled"

  # ldap-server related chart(s)
  - name: "ldap-notifier"
    alias: "nubusLdapNotifier"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.34.2"
    condition: "nubusLdapNotifier.enabled"

  - name: "ldap-server"
    alias: "nubusLdapServer"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.34.2"
    condition: "nubusLdapServer.enabled"

  # portal related chart(s)
  - name: "notifications-api"
    alias: "nubusNotificationsApi"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.63.0"
    condition: "nubusNotificationsApi.enabled"

  - name: "portal-frontend"
    alias: "nubusPortalFrontend"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.63.0"
    condition: "nubusPortalFrontend.enabled"

  - name: "portal-consumer"
    alias: "nubusPortalConsumer"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.63.0"
    condition: "nubusPortalConsumer.enabled"

  - name: "portal-server"
    alias: "nubusPortalServer"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.63.0"
    condition: "nubusPortalServer.enabled"

  # selfservice related chart(s)

  - name: "selfservice-consumer"
    alias: "nubusSelfServiceConsumer"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.14.0"
    condition: "nubusSelfServiceConsumer.enabled"

  # provisioning related chart(s)
  - name: "provisioning"
    alias: "nubusProvisioning"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.49.4"
    condition: "nubusProvisioning.enabled"

  - name: "udm-listener"
    alias: "nubusUdmListener"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.49.3"
    condition: "nubusProvisioning.enabled"

  # keycloak related chart(s)
  - name: "keycloak"
    alias: "keycloak"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.9.3"
    condition: "keycloak.enabled"

  - name: "keycloak-extensions"
    alias: "nubusKeycloakExtensions"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.16.1"
    condition: "nubusKeycloakExtensions.enabled"

  - name: "keycloak-bootstrap"
    alias: "nubusKeycloakBootstrap"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.10.2"
    condition: "nubusKeycloakBootstrap.enabled"

  - name: "stack-data-ums"
    alias: "nubusStackDataUms"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.89.2"
    condition: "nubusStackDataUms.enabled"

  # udm-rest-api related chart(s)
  - name: "udm-rest-api"
    alias: "nubusUdmRestApi"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.29.2"
    condition: "nubusUdmRestApi.enabled"

  # umc related chart(s)
  - name: "umc-gateway"
    alias: "nubusUmcGateway"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.39.0"
    condition: "nubusUmcGateway.enabled"

  - name: "umc-server"
    alias: "nubusUmcServer"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    version: "0.39.0"
    condition: "nubusUmcServer.enabled"
