# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

# Needs to be added to the documentation:

# Cannot be changed
nubusLdapServer:
  ldapServer:
    auth:
      password: "nubusLdapServer.ldapServer.auth.password"

# Can probably be changed
nubusPortalServer:
  portalServer:
    centralNavigation:
      auth:
        sharedSecret: "nubusPortalServer.portalServer.centralNavigation.auth.sharedSecret"
  objectStorage:
    auth:
      accessKeyId: "nubusPortalServer.objectStorage.auth.accessKeyId"
      secretAccessKey: "nubusPortalServer.objectStorage.auth.secretAccessKey"
  udm:
    auth:
      password: "nubusStackData.templateContext.svcPortalServerUserPassword"

# Can be changed
nubusProvisioning:
  nats:
    auth:
      adminPassword: "nubusProvisioning.nats.auth.adminPassword"
  api:
    nats:
      auth:
        password: "nubusProvisioning.api.nats.auth.password"
    auth:
      admin:
        password: "nubusProvisioning.api.auth.admin.password"
      eventsUdm:
        password: "nubusProvisioning.api.auth.eventsUdm.password"
      prefill:
        password: "nubusProvisioning.api.auth.prefill.password"
  dispatcher:
    nats:
      auth:
        password: "nubusProvisioning.dispatcher.nats.auth.password"
  udmTransformer:
    nats:
      auth:
        password: "nubusProvisioning.udmTransformer.nats.auth.password"
  prefill:
    nats:
      auth:
        password: "nubusProvisioning.prefill.nats.auth.password"

# Cannot be changed
nubusStackDataUms:
  templateContext:
    initialPasswordAdministrator: "nubusStackData.templateContext.initialPasswordAdministrator"
    ldapSystemUsers:
    - username: readonly
      password: "nubusStackData.templateContext.ldapSystemUsers[0].password"
    readonlyUserPassword: "nubusStackData.templateContext.readonlyUserPassword"
    svcPortalServerUserPassword: "nubusStackData.templateContext.svcPortalServerUserPassword"

keycloak:
  keycloak:
    auth:
      password: "keycloak.keycloak.auth.password"

nubusKeycloakExtensions:
  smtp:
    auth:
      username: "nubusKeycloakExtensions.smtp.auth.username"

nubusGuardian:
  postgresql:
    auth:
      password: "nubusGuardianpostgresqlauthpassword"

nubusNotificationsApi:
  postgresql:
    auth:
      username: "nubusNotificationsApipostgresqlauthusername"
      password: "nubusNotificationsApipostgresqlauthpassword"

nubusPortalConsumer:
  provisioningApi:
    auth:
      username: "nubusPortalConsumer.provisioningApi.auth.username"
      password: "nubusPortalConsumer.provisioningApi.auth.password"
  objectStorage:
    auth:
      accessKeyId: "nubusPortalConsumer.objectStorage.auth.accessKeyId"
      secretAccessKey: "nubusPortalConsumer.objectStorage.auth.secretAccessKey"

nubusSelfServiceConsumer:
  provisioningApi:
    auth:
      username: "nubusSelfServiceConsumer.provisioningApi.auth.username"
      password: "nubusSelfServiceConsumer.provisioningApi.auth.password"

nubusUdmListener:
  nats:
    auth:
      password: "nubusUdmListener.nats.auth.password"

nubusUmcServer:
  memcached:
    auth:
      username: "nubusUmcServer.memcached.auth.username"
      password: "nubusUmcServer.memcached.auth.password"
  postgresql:
    auth:
      username: "nubusUmcServerpostgresqlauthusername"
      password: "nubusUmcServerpostgresqlauthpassword"
  smtp:
    auth:
      password: "nubusUmcServer.smtp.auth.password"
