# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
{{- if .Values.ingress.favicon.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-favicon
  annotations:
    {{- if .Values.ingress.annotations }}
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.ingress.certManager.issuerRef.name }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default .Values.global.ingressClass | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-portal-tls" .Release.Name) }}
  {{- end }}
  rules:
    - host: {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote }}
      http:
        paths:
          - path: /favicon/
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-portal-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-favicon-well-known
  annotations:
    {{- if .Values.ingress.annotations }}
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.ingress.certManager.issuerRef.name }}"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: "/favicon/$1"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default .Values.global.ingressClass | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-portal-tls" .Release.Name) }}
  {{- end }}
  rules:
    - host: {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote }}
      http:
        paths:
          - path: /(favicon.ico)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-portal-frontend
                port:
                  number: 80
{{- end}}
{{- if .Values.ingress.minio.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-minio-rewrites
  annotations:
    {{- if .Values.ingress.annotations }}
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.ingress.certManager.issuerRef.name }}"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ printf "/%s/portal-assets/icons/$2/$3" .Values.nubusPortalServer.objectStorage.bucketName | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default .Values.global.ingressClass | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote}}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-portal-tls" .Release.Name) }}
  {{- end }}
  rules:
    - host: {{ printf "%s.%s" .Values.global.subDomains.portal .Values.global.domain | quote }}
      http:
        paths:
          - path: /univention/(portal|selfservice)/icons/(logos|entries)/(.*)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-minio" .Release.Name | quote }}
                port:
                  number: 9000
{{- end }}
