# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

{{- if .Values.minio.enabled }}
{{- $nubusMasterPassword := include "nubusTemplates.masterPassword" . -}}
{{- $nubusSecrets := list
  (dict "name" "minio-credentials" "stringData" (dict
    "root-user" (.Values.minio.auth.rootUser | default "admin" | quote )
    "root-password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" ( (.Values.minio.auth.rootUser | default "admin" | quote ) ) ) | sha1sum | quote)
  ))
  (dict "name" "portal-consumer-minio-credentials" "stringData" (dict
      "accessKey" (coalesce .Values.nubusPortalConsumer.objectStorage.auth.accessKeyId (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-consumer-accesskey") | sha1sum) | quote)
      "secretKey" (coalesce .Values.nubusPortalConsumer.objectStorage.auth.secretAccessKey (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-consumer-secretkey") | sha1sum) | quote)
  ))
  (dict "name" "portal-server-minio-credentials" "stringData" (dict
      "accessKey" (coalesce .Values.nubusPortalServer.objectStorage.auth.accessKeyId (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-accesskey") | sha1sum) | quote)
      "secretKey" (coalesce .Values.nubusPortalServer.objectStorage.auth.secretAccessKey (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-secretkey") | sha1sum) | quote)
  ))
-}}

{{- range $secret := $nubusSecrets }}
---
kind: "Secret"
apiVersion: "v1"
type: {{ .type | default "Opaque" | quote }}
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- if .data }}
data:
{{- range $k, $v := .data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- if .stringData }}
stringData:
{{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
...
{{- end }}
{{- end }}
