# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- $nubusMasterPassword := include "nubusTemplates.masterPassword" . -}}
{{- $nubusSecrets := list
  (dict "name" "nubus-credentials" "stringData" (dict
    "admin_password" (include "nubusTemplates.credentials.ldap.users.admin.password" . | quote)
    "user_password" (include "nubusTemplates.credentials.ldap.users.idp.password" . | quote)
  ))
  (dict "name" "postgresql-credentials" "stringData" (dict
    "admin_password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "postgresql-admin") | sha1sum | quote)
    "user_password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "postgresql-user") | sha1sum | quote)
    "replication_password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "postgresql-replication") | sha1sum | quote)
  ))
  (dict "name" "ldap-server-credentials" "stringData" (dict
    "adminPassword" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "keycloak-credentials" "stringData" (dict
    "admin_password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-admin") | sha1sum | quote)
  ))
  (dict "name" "minio-credentials" "stringData" (dict
    "root-user" (.Values.minio.auth.rootUser | default "admin" | quote )
    "root-password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" ( (.Values.minio.auth.rootUser | default "admin" | quote ) ) ) | sha1sum | quote)
  ))
  (dict "name" "portal-listener-minio-credentials" "stringData" (dict
      "accessKey" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-listener-accesskey") | sha1sum | quote)
      "secretKey" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-listener-secretkey") | sha1sum | quote)
  ))
  (dict "name" "portal-server-minio-credentials" "stringData" (dict
      "accessKey" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-accesskey") | sha1sum | quote)
      "secretKey" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-secretkey") | sha1sum | quote)
  ))
  (dict "name" "umc-server-postgresql-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "umc-server") | sha1sum | quote)
  ))
  (dict "name" "notifications-api-postgresql-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "notifications-api") | sha1sum | quote)
  ))
  (dict "name" "keycloak-postgresql-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak") | sha1sum | quote)
  ))
  (dict "name" "keycloak-extensions-postgresql-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-extensions") | sha1sum | quote)
  ))
  (dict "name" "keycloak-extensions-keycloak-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-admin") | sha1sum | quote)
  ))
  (dict "name" "keycloak-extensions-smtp-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-extensions") | sha1sum | quote)
  ))
  (dict "name" "keycloak-bootstrap-ldap-credentials" "stringData" (dict
      "password" (include "nubusTemplates.credentials.ldap.users.readonly.password" . | quote)
  ))
  (dict "name" "keycloak-bootstrap-keycloak-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-admin") | sha1sum | quote)
  ))
  (dict "name" "udm-listener-ldap-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "stack-data-swp-ldap-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "selfservice-listener-ldap-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "udm-rest-api-ldap-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "self-service-ldap-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "umc-server-ldap-credentials" "stringData" (dict
      "ldap.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
      "machine.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "stack-data-udm-rest-api-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "umc-server-udm-rest-api-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "portal-listener-ldap-credentials" "stringData" (dict
    "ldap.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
    "machine.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-udm-listener-ldap-credentials" "stringData" (dict
    "ldap.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
    "machine.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "portal-listener-udm-rest-api-credentials" "stringData" (dict
      "password" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "readonly-ldap-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "readonly") | sha1sum | quote)
  ))
  (dict "name" "provisioning-events-and-consumer-api-nats-credentials" "stringData" (dict
      "password" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-events-and-consumer-api") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-dispatcher-nats-credentials" "stringData" (dict
      "password" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-dispatcher") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-prefill-nats-credentials" "stringData" (dict
      "password" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-prefill") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-udm-transformer-nats-credentials" "stringData" (dict
      "NATS_USER" "udmtransformer"
      "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm-transformer") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-udm-transformer-api-credentials" "stringData" (dict
    "EVENTS_USERNAME_UDM" "udm"
    "EVENTS_PASSWORD_UDM" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm") | sha1sum | quote)
  ))
  (dict "name" "provisioning-udm-transformer-ldap-credentials" "stringData" (dict
      "LDAP_BIND_PW" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "selfservice-listener-nats-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "selfservice-listener") | sha1sum | quote)
  ))
  (dict "name" "udm-rest-api-credentials" "stringData" (dict
      "ldap.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
      "machine.secret" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "umc-server-memcached-credentials" "stringData" (dict
      "memcached-password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "umc-server") | sha1sum | quote)
  ))
  (dict "name" "umc-server-smtp-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "umc-server") | sha1sum | quote)
  ))
  (dict "name" "umc-server-ldap-tls" "stringData" (dict
    "ca.crt" ""
    "tls.key" ""
    "tls.crt" ""
  ))
  (dict "name" "portal-listener-ldap-tls" "stringData" (dict
    "ca.crt" ""
    "tls.key" ""
    "tls.crt" ""
  ))
  (dict "name" "provisioning-udm-listener-ldap-tls" "stringData" (dict
    "ca.crt" ""
    "tls.key" ""
    "tls.crt" ""
  ))
  (dict "name" "provisioning-nats-credentials" "stringData" (dict
    "admin_password" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-nats") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-api-credentials" "stringData" (dict
    "NATS_USER" "api"
    "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-api") | sha1sum) | quote)
    "ADMIN_NATS_USER" "admin"
    "ADMIN_NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-nats") | sha1sum) | quote)
    "ADMIN_USERNAME" "admin"
    "ADMIN_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-admin") | sha1sum | quote)
    "PREFILL_USERNAME" "prefill"
    "PREFILL_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-prefill") | sha1sum | quote)
    "EVENTS_USERNAME_UDM" "udm"
    "EVENTS_PASSWORD_UDM" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm") | sha1sum | quote)
  ))
  (dict "name" "provisioning-dispatcher-credentials" "stringData" (dict
    "UDM_USERNAME" "cn=admin"
    "UDM_PASSWORD" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
    "NATS_USER" "dispatcher"
    "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-dispatcher") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-prefill-credentials" "stringData" (dict
    "UDM_USERNAME" "cn=admin"
    "UDM_PASSWORD" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
    "NATS_USER" "prefill"
    "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-prefill") | sha1sum) | quote)
    "PREFILL_USERNAME" "prefill"
    "PREFILL_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-prefill") | sha1sum | quote)
  ))
  (dict "name" "provisioning-udm-listener-credentials" "stringData" (dict
    "NATS_USER" "udmlistener"
    "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm-listener") | sha1sum) | quote)
    "EVENTS_USERNAME_UDM" "udm"
    "EVENTS_PASSWORD_UDM" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm") | sha1sum | quote)
  ))
  (dict "name" "provisioning-udm-transformer-credentials" "stringData" (dict
    "NATS_USER" "udmtransformer"
    "NATS_PASSWORD" (printf "nbs_%s" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm-transformer") | sha1sum) | quote)
    "EVENTS_USERNAME_UDM" "udm"
    "EVENTS_PASSWORD_UDM" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-udm") | sha1sum | quote)
  ))
  (dict "name" "provisioning-register-consumers-credentials" "stringData" (dict
    "ADMIN_USERNAME" "admin"
    "ADMIN_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "provisioning-admin") | sha1sum | quote)
  ))
  (dict "name" "selfservice-listener-credentials" "stringData" (dict
    "NATS_USER" "selfservice"
    "NATS_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "selfservice-listener") | sha1sum | quote)
    "PROVISIONING_API_PASSWORD" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "selfservice-listener") | sha1sum | quote)
    "UMC_ADMIN_PASSWORD" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "provisioning-register-consumers-json-secrets" "stringData" (dict
    "selfservice.json" (printf "{ \"name\": \"selfservice\", \"realms_topics\": [[\"udm\", \"groups/group\"]], \"request_prefill\": true, \"password\": \"%s\" }"
      (derivePassword 1 "long" $nubusMasterPassword "nubus" "selfservice-listener" | sha1sum)|quote)
  ))
  (dict "name" "guardian-keycloak-client-secret" "stringData" (dict
    "oauthAdapterM2mSecret" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "guardian-keycloak-client-secret") | sha1sum | quote)
  ))
  (dict "name" "guardian-udm-secret" "stringData" (dict
    "udmDataAdapterUsername" "cn=admin"
    "udmDataAdapterPassword" (coalesce .Values.credentialOverride.ldapServer.adminPassword (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "ldap-server") | sha1sum) | quote)
  ))
  (dict "name" "guardian-provisioning-secret" "stringData" (dict
    "adminPassword" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "keycloak-admin") | sha1sum | quote)
    "managementApiClientSecret" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "guardian-keycloak-client-secret") | sha1sum | quote)
  ))
  (dict "name" "guardian-management-api-postgresql-credentials" "stringData" (dict
      "password" (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "guardian-management-api") | sha1sum | quote)
  ))

-}}

{{- range $secret := $nubusSecrets }}
---
kind: "Secret"
apiVersion: "v1"
type: {{ .type | default "Opaque" | quote }}
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- if .data }}
data:
{{- range $k, $v := .data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- if .stringData }}
stringData:
{{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
...
{{- end }}
