# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

apiVersion: v2
name: certificate
description: Utility chart to deploy a TLS certificate
type: application
version: 0.1.0
